# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HappyHouse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HappyHouse

  target 'HappyHouseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HappyHouseUITests' do
    # Pods for testing
  end

# Podfile
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
    pod 'RxAlamofire'
    pod 'Firebase/Storage'
    pod 'SnapKit', '~> 5.0.0'
    pod 'Then'
    pod 'GoogleSignIn'
end
